### ISSUE TITLE
Login/logout rest-api information

### ISSUE THREAD

**Issue by ayian2004** [qlack/QLACK-WebDesktop#36]
On the web-desktop main application expose a new unprotected rest-api end-point, which will receive as parameter the username of an existing user and will return a json object with all login/logout history of the requested user.

**Comment by NMichas** [comment]
We can't provide such sensitive info over an unprotected endpoint.

**Comment by ayian2004** [comment]
On the web-desktop main application expose a new **protected** rest-api end-point, which will receive as parameter the username of an existing user and will return a json object with all login/logout history of the requested user.
